include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:

analyzer:
  errors:
    public_member_api_docs: ignore
    lines_longer_than_80_chars: ignore
    invalid_assignment: ignore
    cascade_invocations: ignore
    avoid_dynamic_calls: ignore
    inference_failure_on_function_invocation: ignore
    inference_failure_on_generic_invocation: ignore
    invalid_annotation_target: ignore
    use_string_buffers: ignore
    use_setters_to_change_properties: ignore
    sort_pub_dependencies: ignore
    one_member_abstracts: ignore