name: oz_vpn
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # State Management
  get: ^4.6.6
  # Responsive UI
  flutter_screenutil: ^5.9.3
  # UI Components
  flutter_svg: ^2.0.10+1
  flutter_bounceable: ^1.1.0
  # Local Storage
  get_storage: ^2.1.1
  # Date format
  intl: ^0.19.0
  # Cancelable Operation
  async: ^2.11.0
  # Webview
  url_launcher: ^6.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/langs/
    
  fonts:
    - family: Gilroy Bold
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf
    - family: Gilroy Medium
      fonts:
        - asset: assets/fonts/Gilroy-Medium.ttf
    - family: Gilroy Regular
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
    - family: Gilroy SemiBold
      fonts:
        - asset: assets/fonts/Gilroy-SemiBold.ttf
    - family: Gilroy Thin
      fonts:
        - asset: assets/fonts/Gilroy-Thin.ttf
    - family: Gilroy ExtraBold
      fonts:
        - asset: assets/fonts/Gilroy-ExtraBold.ttf
    - family: Gilroy SemiBoldItalic
      fonts:
        - asset: assets/fonts/Gilroy-SemiBoldItalic.ttf



